### ISSUE TITLE
Altimeter Not Smoothing Values

### ISSUE THREAD

**Issue by tkollmorgen** [TerraClear/altipi#5] opened 2019-06-13 21:40 UTC
## Describe the Bug
For each camera trigger the altimeter takes several values and writes them to the debug.  From this debug an average should be calculated and written to the official altimeter log.  No average is being taken, instead only the largest value is being recorded.

## How To Reproduce
View altimeter debug and associated altimeter log

## Expected Behavior
Smoothing algorithm should write an average of the values to the official altimeter log.

## Environment 

- git hash:

**Comment by JAMorrow** [comment] 2019-06-17 16:18
In v0.09 I've actually backed out any smoothing we do so we can tell if the onboard altimeter filter smoothing will work instead.  This would simplify the code we have to maintain.  If it looks like we are getting good values from the altimeter, I prefer to not introduce error via averaging on our side.

Can also experiment with linear regression to smooth the values--will consult with Elisabeth.

**Comment by JAMorrow** [comment] 2019-06-24 16:11
Closing as fixed with enabling the altimeter's on board smoothing.

**Closed as completed by JAMorrow** 2019-06-24 16:11 UTC
Labels: bug
